#!/usr/bin/env node
// A5 — seam-graph acceptance probe (tmp/plans/assembly-from-pattern/01-PLAN.md §2, lane A).
//
// Runs lib/assembly-skeleton/geometry on three real CLO files through the product DXF parser and
// scores it against the visual truth of the 09.10 probe (probe/truth/*.json). Gates:
//   SS26-005  recall ≥ 67 % and precision ≥ 53 % (no worse than the probe);
//   Allsizes  no seam along the centre front (button opening), no yoke ↔ yoke-facing shoulder seam;
//   blazer    ambiguous ≤ 60 % of chosen seams (probe: 90 %).
// NEGATIVE CONTROL: the same run with the hand rule OFF must lose precision on SS26-005 — a probe
// whose numbers do not move when a rule is removed is not measuring that rule.
//
// Usage: node scripts/assembly-skeleton/seams.mjs        (SKELETON_VERBOSE=1 lists every seam)
// Data:  SKELETON_PLANS=<dir with assembly-from-pattern/ and pdf-to-dxf/>, default ../tmp/plans
//        next to the repo.

import { build } from 'esbuild';
import { readFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';

const here = dirname(fileURLToPath(import.meta.url));
const outfile = resolve(tmpdir(), `skeleton-seams-${process.pid}.mjs`);
await build({
  entryPoints: [resolve(here, 'seams-entry.ts')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  outfile,
  logLevel: 'warning',
});
const mod = await import(pathToFileURL(outfile).href);

const plans = process.env.SKELETON_PLANS ?? resolve(here, '../../../tmp/plans');
const probeDir = resolve(plans, 'assembly-from-pattern/probe');
const corpus = resolve(plans, 'pdf-to-dxf/corpus/dxf-clo');
const verbose = process.env.SKELETON_VERBOSE === '1';

const FILES = [
  {
    id: 'ss26',
    label: 'SS26-005 shirt',
    dxf: resolve(probeDir, 'data/ss26-005-shirt.dxf'),
    truth: 'shirt-M',
    category: 'shirt',
  },
  {
    id: 'allsizes',
    label: 'Allsizes (yoke shirt)',
    dxf: resolve(corpus, 'Allsizes_with_notches.dxf'),
    truth: 'allsizes-M',
    category: 'shirt',
  },
  {
    id: 'blazer',
    label: 'blazer (46, lined)',
    dxf: resolve(corpus, 'blazer.dxf'),
    truth: 'blazer-M',
    category: 'jacket-lined',
  },
];

const readJson = async (p) => JSON.parse(await readFile(p, 'utf8'));

// The truth labels name the 09.10 probe's edges; its out/*.json carries the geometry that maps them
// (resample + edge index ranges). An older dump without them is regenerated by the same probe code
// into tmp — deterministic, and checked to give the same listing as the one the truth was read from.
async function probeGeometry(f) {
  const json = await readJson(resolve(probeDir, 'out', `${f.truth}.json`));
  if (json.edgeIdx && json.pieces?.[0]?.rs) return json;
  const prefix = resolve(tmpdir(), `skeleton-probe-${process.pid}-${f.truth}`);
  execFileSync(process.execPath, [resolve(probeDir, 'seamgraph.mjs'), f.dxf, 'M', prefix], {
    stdio: 'ignore',
  });
  return readJson(`${prefix}.json`);
}
const pct = (x) => `${Math.round(x * 100)}%`.padStart(4);

// Silence dxf-parser's per-tag chatter (it prints through console.log); keep our own output.
const warn = console.warn;
const log = console.log;
console.warn = () => {};
console.log = () => {};
const loaded = [];
for (const f of FILES) {
  const buf = await readFile(f.dxf);
  const bytes = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
  const { facts, origin } = await mod.loadFacts(bytes, 'M', f.category);
  loaded.push({
    ...f,
    facts,
    origin,
    truthJson: await readJson(resolve(probeDir, 'truth', `${f.truth}.json`)),
    probeJson: await probeGeometry(f),
  });
}
console.warn = warn;
console.log = log;

const ALL = mod.ALL_RULES;
const PROBE = mod.PROBE_RULES;
const CONFIGS = [
  { name: 'probe rules (hand only)', rules: PROBE },
  { name: '  └ NEG: probe, hand OFF', rules: { ...PROBE, hand: false } },
  { name: 'full rules', rules: ALL },
  {
    name: '  └ amb. strict (no equivalence)',
    rules: { ...ALL, equivRect: false, equivLayers: false },
  },
  { name: '  └ amb. rect symmetry only', rules: { ...ALL, equivLayers: false } },
  { name: '  └ NEG: full, hand OFF', rules: { ...ALL, hand: false } },
  ...Object.keys(ALL)
    .filter((k) => !['hand', 'equivRect', 'equivLayers'].includes(k))
    .map((k) => ({ name: `  └ ablate: ${k} OFF`, rules: { ...ALL, [k]: false } })),
];

function evaluate(f, rules) {
  const { graph, ms } = mod.run(f.facts, rules);
  const mapper = mod.labelMapper(f.probeJson, graph.pieces, f.origin);
  const s = mod.score(graph, f.truthJson, mapper.map);
  return { graph, ms, s, mapper };
}

const results = new Map();
console.log(
  '\nconfig                          │ SS26-005 rec/prec/amb │ Allsizes rec/prec/amb │ blazer rec/amb',
);
console.log(
  '────────────────────────────────┼───────────────────────┼───────────────────────┼───────────────',
);
for (const c of CONFIGS) {
  const row = loaded.map((f) => evaluate(f, c.rules));
  results.set(c.name, row);
  const [a, b, z] = row.map((r) => r.s);
  console.log(
    `${c.name.padEnd(32)}│ ${pct(a.recall)} ${pct(a.precision)} ${pct(a.ambiguousShare)} (${String(a.chosen).padStart(2)}) │` +
      ` ${pct(b.recall)} ${pct(b.precision)} ${pct(b.ambiguousShare)} (${String(b.chosen).padStart(2)}) │` +
      ` ${pct(z.recall)} ${pct(z.ambiguousShare)} (${z.chosen})`,
  );
}

const detail =
  results.get(process.env.SKELETON_DETAIL ?? 'full rules') ?? results.get('full rules');
const full = results.get('full rules');
for (let i = 0; i < loaded.length; i++) {
  const f = loaded[i];
  const { graph, ms, s, mapper } = detail[i];
  console.log(
    `\n── ${f.label}: ${f.facts.pieces.length} pieces, ${graph.pieces.reduce((n, p) => n + p.edges.length, 0)} edges, ${ms.toFixed(0)} ms`,
  );
  console.log(
    `   truth ${s.truth} · chosen ${s.chosen} · recovered ${s.recovered} · acceptable ${s.acceptable} · wrong ${s.wrong} · ambiguous ${s.ambiguous}`,
  );
  if (mapper.offset.length)
    console.log(
      `   note: truth edges mapped across a contour offset: ${[...new Set(mapper.offset)].join(', ')}`,
    );
  if (mapper.unmapped.length)
    console.log(`   ⚠ truth labels not mapped onto product edges: ${mapper.unmapped.join(', ')}`);
  console.log(`   missed: ${s.missed.join('; ') || '—'}`);
  console.log(
    `   wrong${f.id === 'blazer' ? ' (PARTIAL truth: = not among the 10 seams identified by eye)' : ''}:  ${s.wrongPairs.join('; ') || '—'}`,
  );
  const closures = graph.rejected.filter((c) => c.kind === 'closure-not-seam');
  if (closures.length)
    console.log(
      `   closures: ${closures.map((c) => `${c.a}~${c.b} (${c.evidence.rule})`).join('; ')}`,
    );
  for (const w of graph.warnings) console.log(`   warning: ${w}`);
  if (verbose) {
    const rules =
      CONFIGS.find((c) => c.name === (process.env.SKELETON_DETAIL ?? 'full rules'))?.rules ?? ALL;
    console.log('   truth pairs:');
    for (const line of mod.explainTruth(graph, f.truthJson, mapper.map, rules))
      console.log(`     ${line}`);
    console.log('   chosen:');
    for (const c of graph.chosen) {
      const e = c.evidence;
      console.log(
        `     ${c.score.toFixed(2)} ${c.a.padEnd(14)} ↔ ${c.b.padEnd(14)} Δ${e.dLenMm.toFixed(1)} ns=${e.notchScore} ${e.twin !== 'none' ? e.twin : ''}${e.self ? ' self' : ''}${e.rule ? ` [${e.rule}]` : ''}${c.ambiguousWith ? ` amb(${c.ambiguousWith.map((q) => `${q.a}~${q.b}`).join(', ')})` : ''}`,
      );
    }
  }
}

// ── gates ────────────────────────────────────────────────────────────────────────────────────
let failures = 0;
const check = (ok, label, detail) => {
  console.log(`${ok ? '  ok  ' : '  FAIL'} ${label}${detail ? ` — ${detail}` : ''}`);
  if (!ok) failures++;
};
console.log('\n── gates (full rules)');
const [ss, all, bl] = full;
check(ss.s.recall >= 0.67, 'SS26-005 recall ≥ 67 %', pct(ss.s.recall).trim());
check(ss.s.precision >= 0.53, 'SS26-005 precision ≥ 53 %', pct(ss.s.precision).trim());

const am = all.mapper.map;
const cf = mod.pairsBetween(all.graph, am('FP_L#2'), am('FP_R#2'));
check(
  cf.length === 0,
  'Allsizes: no seam along the centre front (FP_L#2 ~ FP_R#2)',
  cf.join(', ') || 'none',
);
const cfClosure = all.graph.rejected.filter(
  (c) =>
    c.kind === 'closure-not-seam' &&
    mod.pairsBetween({ chosen: [c] }, am('FP_L#2'), am('FP_R#2')).length > 0,
);
check(
  cfClosure.length === 1,
  'Allsizes: the centre front is reported as a closure, not a seam',
  cfClosure.map((c) => `${c.a}~${c.b} (${c.evidence.rule})`).join(', ') || 'not reported',
);
const shoulders = mod.pairsBetween(
  all.graph,
  [...am('BP#1'), ...am('BP#3')],
  [...am('BP_2#1'), ...am('BP_2#3')],
);
check(
  shoulders.length === 0,
  'Allsizes: no yoke ↔ yoke-facing seam on the shoulders',
  shoulders.join(', ') || 'none',
);
const yokeLayers = mod.pairsBetween(
  all.graph,
  all.graph.pieces.find((p) => p.pieceKey === 'BP').edges.map((e) => e.id),
  all.graph.pieces.find((p) => p.pieceKey === 'BP_2').edges.map((e) => e.id),
);
check(
  yokeLayers.length <= 1,
  'Allsizes: yoke layers meet along one edge at most',
  yokeLayers.join(', ') || 'none',
);
check(
  bl.s.ambiguousShare <= 0.6,
  'blazer: ambiguous ≤ 60 % of chosen',
  `${bl.s.ambiguous}/${bl.s.chosen} = ${pct(bl.s.ambiguousShare).trim()}`,
);

for (const [label, neg, pos] of [
  ['probe rules', '  └ NEG: probe, hand OFF', 'probe rules (hand only)'],
  ['full rules', '  └ NEG: full, hand OFF', 'full rules'],
]) {
  const n = results.get(neg)[0].s;
  const p = results.get(pos)[0].s;
  check(
    n.precision < p.precision,
    `negative control (${label}): hand rule OFF loses SS26-005 precision`,
    `${pct(p.precision).trim()} → ${pct(n.precision).trim()}`,
  );
}

// Ties (equal-length unnotched edges, L/R sides of a symmetric piece) are broken by input order.
// A number that holds only in one order is luck, not the rules: the same gates on reversed input.
console.log('\n── order stability (full rules, pieces in reverse order)');
const reversed = loaded.map((f) =>
  evaluate({ ...f, facts: { ...f.facts, pieces: [...f.facts.pieces].reverse() } }, ALL),
);
for (let i = 0; i < loaded.length; i++) {
  const r = reversed[i].s;
  console.log(
    `   ${loaded[i].label.padEnd(24)} recall ${pct(r.recall)} precision ${pct(r.precision)} ambiguous ${pct(r.ambiguousShare)} (${r.chosen})`,
  );
}
check(
  reversed[0].s.recall >= 0.67 && reversed[0].s.precision >= 0.53,
  'SS26-005 gates hold in reverse order',
  `${pct(reversed[0].s.recall).trim()} / ${pct(reversed[0].s.precision).trim()}`,
);
check(
  reversed[2].s.ambiguousShare <= 0.6,
  'blazer ambiguity gate holds in reverse order',
  pct(reversed[2].s.ambiguousShare).trim(),
);
const strict = results.get('  └ amb. strict (no equivalence)')[2].s;
console.log(
  `   info: blazer ambiguity with NO equivalence (rect sides / identical layers count as choices): ${strict.ambiguous}/${strict.chosen} = ${pct(strict.ambiguousShare).trim()}`,
);

console.log(failures ? `\n${failures} gate(s) FAILED` : '\nall gates green');
process.exit(failures ? 1 : 0);
