// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */
// @ts-nocheck

export type MetricsGranularity =
  | "METRICS_GRANULARITY_UNSPECIFIED"
  | "METRICS_GRANULARITY_DAY"
  | "METRICS_GRANULARITY_WEEK"
  | "METRICS_GRANULARITY_MONTH";
export type CompareMode =
  | "COMPARE_MODE_UNSPECIFIED"
  | "COMPARE_MODE_NONE"
  | "COMPARE_MODE_PREVIOUS_PERIOD"
  | "COMPARE_MODE_SAME_PERIOD_LAST_YEAR";
export type GetDictionaryRequest = {
};

export type GetDictionaryResponse = {
  dictionary: common_Dictionary | undefined;
  rates: common_CurrencyMap | undefined;
};

export type common_Dictionary = {
  categories: common_Category[] | undefined;
  measurements: common_MeasurementName[] | undefined;
  orderStatuses: common_OrderStatus[] | undefined;
  paymentMethods: common_PaymentMethod[] | undefined;
  shipmentCarriers: common_ShipmentCarrier[] | undefined;
  sizes: common_Size[] | undefined;
  collections: common_Collection[] | undefined;
  languages: common_Language[] | undefined;
  siteEnabled: boolean | undefined;
  maxOrderItems: number | undefined;
  baseCurrency: string | undefined;
  bigMenu: boolean | undefined;
  announce: common_Announce | undefined;
  orderExpirationSeconds: number | undefined;
  complimentaryShippingPrices: { [key: string]: googletype_Decimal } | undefined;
  isProd: boolean | undefined;
};

// Category represents a hierarchical category structure
export type common_Category = {
  id: number | undefined;
  name: string | undefined;
  levelId: number | undefined;
  level: string | undefined;
  parentId: number | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
};

export type common_MeasurementName = {
  id: number | undefined;
  name: string | undefined;
};

export type common_OrderStatus = {
  id: number | undefined;
  name: common_OrderStatusEnum | undefined;
};

export type common_OrderStatusEnum =
  | "ORDER_STATUS_ENUM_UNKNOWN"
  | "ORDER_STATUS_ENUM_PLACED"
  | "ORDER_STATUS_ENUM_AWAITING_PAYMENT"
  | "ORDER_STATUS_ENUM_CONFIRMED"
  | "ORDER_STATUS_ENUM_SHIPPED"
  | "ORDER_STATUS_ENUM_DELIVERED"
  | "ORDER_STATUS_ENUM_CANCELLED"
  | "ORDER_STATUS_ENUM_PENDING_RETURN"
  | "ORDER_STATUS_ENUM_REFUND_IN_PROGRESS"
  | "ORDER_STATUS_ENUM_REFUNDED"
  | "ORDER_STATUS_ENUM_PARTIALLY_REFUNDED";
// PaymentMethod represents the payment_method table
export type common_PaymentMethod = {
  id: number | undefined;
  name: common_PaymentMethodNameEnum | undefined;
  allowed: boolean | undefined;
};

export type common_PaymentMethodNameEnum =
  | "PAYMENT_METHOD_NAME_ENUM_UNKNOWN"
  | "PAYMENT_METHOD_NAME_ENUM_CARD"
  | "PAYMENT_METHOD_NAME_ENUM_CARD_TEST";
export type common_ShipmentCarrier = {
  id: number | undefined;
  shipmentCarrier: common_ShipmentCarrierInsert | undefined;
  prices: common_ShipmentCarrierPrice[] | undefined;
  allowedRegions: common_ShippingRegion[] | undefined;
};

export type common_ShipmentCarrierInsert = {
  carrier: string | undefined;
  allowed: boolean | undefined;
  description: string | undefined;
  trackingUrl: string | undefined;
  expectedDeliveryTime: string | undefined;
};

export type common_ShipmentCarrierPrice = {
  currency: string | undefined;
  price: googletype_Decimal | undefined;
};

// A representation of a decimal value, such as 2.5. Clients may convert values
// into language-native decimal formats, such as Java's [BigDecimal][] or
// Python's [decimal.Decimal][].
// [BigDecimal]:
// https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html
// [decimal.Decimal]: https://docs.python.org/3/library/decimal.html
export type googletype_Decimal = {
  // The decimal value, as a string.
  // The string representation consists of an optional sign, `+` (`U+002B`)
  // or `-` (`U+002D`), followed by a sequence of zero or more decimal digits
  // ("the integer"), optionally followed by a fraction, optionally followed
  // by an exponent.
  // The fraction consists of a decimal point followed by zero or more decimal
  // digits. The string must contain at least one digit in either the integer
  // or the fraction. The number formed by the sign, the integer and the
  // fraction is referred to as the significand.
  // The exponent consists of the character `e` (`U+0065`) or `E` (`U+0045`)
  // followed by one or more decimal digits.
  // Services **should** normalize decimal values before storing them by:
  // - Removing an explicitly-provided `+` sign (`+2.5` -> `2.5`).
  // - Replacing a zero-length integer value with `0` (`.5` -> `0.5`).
  // - Coercing the exponent character to lower-case (`2.5E8` -> `2.5e8`).
  // - Removing an explicitly-provided zero exponent (`2.5e0` -> `2.5`).
  // Services **may** perform additional normalization based on its own needs
  // and the internal decimal implementation selected, such as shifting the
  // decimal point and exponent value together (example: `2.5e-1` <-> `0.25`).
  // Additionally, services **may** preserve trailing zeroes in the fraction
  // to indicate increased precision, but are not required to do so.
  // Note that only the `.` character is supported to divide the integer
  // and the fraction; `,` **should not** be supported regardless of locale.
  // Additionally, thousand separators **should not** be supported. If a
  // service does support them, values **must** be normalized.
  // The ENBF grammar is:
  // DecimalString =
  // [Sign] Significand [Exponent];
  // Sign = '+' | '-';
  // Significand =
  // Digits ['.'] [Digits] | [Digits] '.' Digits;
  // Exponent = ('e' | 'E') [Sign] Digits;
  // Digits = { '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' };
  // Services **should** clearly document the range of supported values, the
  // maximum supported precision (total number of digits), and, if applicable,
  // the scale (number of digits after the decimal point), as well as how it
  // behaves when receiving out-of-bounds values.
  // Services **may** choose to accept values passed as input even when the
  // value has a higher precision or scale than the service supports, and
  // **should** round the value to fit the supported scale. Alternatively, the
  // service **may** error with `400 Bad Request` (`INVALID_ARGUMENT` in gRPC)
  // if precision would be lost.
  // Services **should** error with `400 Bad Request` (`INVALID_ARGUMENT` in
  // gRPC) if the service receives a value outside of the supported range.
  value: string | undefined;
};

export type common_ShippingRegion =
  | "SHIPPING_REGION_UNKNOWN"
  | "SHIPPING_REGION_AFRICA"
  | "SHIPPING_REGION_AMERICAS"
  | "SHIPPING_REGION_ASIA_PACIFIC"
  | "SHIPPING_REGION_EUROPE"
  | "SHIPPING_REGION_MIDDLE_EAST";
export type common_Size = {
  id: number | undefined;
  name: string | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
};

export type common_Collection = {
  name: string | undefined;
  countMen: number | undefined;
  countWomen: number | undefined;
};

export type common_Language = {
  id: number | undefined;
  code: string | undefined;
  name: string | undefined;
  isDefault: boolean | undefined;
  isActive: boolean | undefined;
};

export type common_Announce = {
  link: string | undefined;
  translations: common_AnnounceTranslation[] | undefined;
};

export type common_AnnounceTranslation = {
  languageId: number | undefined;
  text: string | undefined;
};

// CurrencyMap represents a map of currency codes to their rates.
export type common_CurrencyMap = {
  currencies: { [key: string]: common_CurrencyRate } | undefined;
};

// CurrencyRate represents the rate of a currency with a description.
export type common_CurrencyRate = {
  description: string | undefined;
  rate: googletype_Decimal | undefined;
};

export type UploadContentImageRequest = {
  rawB64Image: string | undefined;
};

export type UploadContentImageResponse = {
  media: common_MediaFull | undefined;
};

export type common_MediaFull = {
  // Media ID
  id: number | undefined;
  // Media created date
  createdAt: wellKnownTimestamp | undefined;
  // media
  media: common_MediaItem | undefined;
};

// Encoded using RFC 3339, where generated output will always be Z-normalized
// and uses 0, 3, 6 or 9 fractional digits.
// Offsets other than "Z" are also accepted.
type wellKnownTimestamp = string;

export type common_MediaItem = {
  // Full-size media URL
  fullSize: common_MediaInfo | undefined;
  // Thumbnail media URL
  thumbnail: common_MediaInfo | undefined;
  // Compressed media URL
  compressed: common_MediaInfo | undefined;
  // BlurHash
  blurhash: string | undefined;
};

export type common_MediaInfo = {
  // Media URL
  mediaUrl: string | undefined;
  // width
  width: number | undefined;
  // height
  height: number | undefined;
};

export type UploadContentVideoRequest = {
  raw: string | undefined;
  contentType: string | undefined;
};

export type UploadContentVideoResponse = {
  media: common_MediaFull | undefined;
};

export type ListObjectsPagedRequest = {
  limit: number | undefined;
  offset: number | undefined;
  orderFactor: common_OrderFactor | undefined;
};

export type common_OrderFactor =
  | "ORDER_FACTOR_UNKNOWN"
  | "ORDER_FACTOR_ASC"
  | "ORDER_FACTOR_DESC";
export type ListObjectsPagedResponse = {
  list: common_MediaFull[] | undefined;
};

export type DeleteFromBucketRequest = {
  id: number | undefined;
};

export type DeleteFromBucketResponse = {
};

export type UpsertProductRequest = {
  id: number | undefined;
  product: common_ProductNew | undefined;
};

export type common_ProductNew = {
  product: common_ProductInsert | undefined;
  sizeMeasurements: common_SizeWithMeasurementInsert[] | undefined;
  mediaIds: number[] | undefined;
  tags: common_ProductTagInsert[] | undefined;
  prices: common_ProductPriceInsert[] | undefined;
};

export type common_ProductInsert = {
  productBodyInsert: common_ProductBodyInsert | undefined;
  thumbnailMediaId: number | undefined;
  translations: common_ProductInsertTranslation[] | undefined;
  secondaryThumbnailMediaId: number | undefined;
  prices: common_ProductPriceInsert[] | undefined;
};

export type common_ProductBodyInsert = {
  preorder: wellKnownTimestamp | undefined;
  brand: string | undefined;
  color: string | undefined;
  colorHex: string | undefined;
  countryOfOrigin: string | undefined;
  salePercentage: googletype_Decimal | undefined;
  topCategoryId: number | undefined;
  subCategoryId: number | undefined;
  typeId: number | undefined;
  modelWearsHeightCm: number | undefined;
  modelWearsSizeId: number | undefined;
  careInstructions: string | undefined;
  composition: string | undefined;
  hidden: boolean | undefined;
  targetGender: common_GenderEnum | undefined;
  version: string | undefined;
  collection: string | undefined;
  fit: string | undefined;
};

export type common_GenderEnum =
  | "GENDER_ENUM_UNKNOWN"
  | "GENDER_ENUM_MALE"
  | "GENDER_ENUM_FEMALE"
  | "GENDER_ENUM_UNISEX";
export type common_ProductInsertTranslation = {
  languageId: number | undefined;
  name: string | undefined;
  description: string | undefined;
};

export type common_ProductPriceInsert = {
  currency: string | undefined;
  price: googletype_Decimal | undefined;
};

export type common_SizeWithMeasurementInsert = {
  productSize: common_ProductSizeInsert | undefined;
  measurements: common_ProductMeasurementInsert[] | undefined;
};

export type common_ProductSizeInsert = {
  quantity: googletype_Decimal | undefined;
  sizeId: number | undefined;
};

export type common_ProductMeasurementInsert = {
  measurementNameId: number | undefined;
  measurementValue: googletype_Decimal | undefined;
};

export type common_ProductTagInsert = {
  tag: string | undefined;
};

export type UpsertProductResponse = {
  id: number | undefined;
};

export type GetProductsPagedRequest = {
  limit: number | undefined;
  offset: number | undefined;
  sortFactors: common_SortFactor[] | undefined;
  orderFactor: common_OrderFactor | undefined;
  filterConditions: common_FilterConditions | undefined;
  showHidden: boolean | undefined;
};

export type common_SortFactor =
  | "SORT_FACTOR_UNKNOWN"
  | "SORT_FACTOR_CREATED_AT"
  | "SORT_FACTOR_UPDATED_AT"
  | "SORT_FACTOR_NAME"
  | "SORT_FACTOR_PRICE";
export type common_FilterConditions = {
  from: string | undefined;
  to: string | undefined;
  currency: string | undefined;
  onSale: boolean | undefined;
  gender: common_GenderEnum[] | undefined;
  color: string | undefined;
  topCategoryIds: number[] | undefined;
  subCategoryIds: number[] | undefined;
  typeIds: number[] | undefined;
  sizesIds: number[] | undefined;
  preorder: boolean | undefined;
  byTag: string | undefined;
  collections: string[] | undefined;
};

export type GetProductsPagedResponse = {
  products: common_Product[] | undefined;
};

export type common_Product = {
  id: number | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  slug: string | undefined;
  sku: string | undefined;
  productDisplay: common_ProductDisplay | undefined;
  prices: common_ProductPrice[] | undefined;
  soldOut: boolean | undefined;
};

export type common_ProductDisplay = {
  productBody: common_ProductBody | undefined;
  thumbnail: common_MediaFull | undefined;
  secondaryThumbnail: common_MediaFull | undefined;
};

export type common_ProductBody = {
  productBodyInsert: common_ProductBodyInsert | undefined;
  translations: common_ProductInsertTranslation[] | undefined;
};

export type common_ProductPrice = {
  currency: string | undefined;
  price: googletype_Decimal | undefined;
};

export type GetProductByIDRequest = {
  id: number | undefined;
};

export type GetProductByIDResponse = {
  product: common_ProductFull | undefined;
};

export type common_ProductFull = {
  product: common_Product | undefined;
  sizes: common_ProductSize[] | undefined;
  measurements: common_ProductMeasurement[] | undefined;
  media: common_MediaFull[] | undefined;
  tags: common_ProductTag[] | undefined;
};

export type common_ProductSize = {
  id: number | undefined;
  quantity: googletype_Decimal | undefined;
  productId: number | undefined;
  sizeId: number | undefined;
};

export type common_ProductMeasurement = {
  id: number | undefined;
  productId: number | undefined;
  productSizeId: number | undefined;
  measurementNameId: number | undefined;
  measurementValue: googletype_Decimal | undefined;
};

export type common_ProductTag = {
  id: number | undefined;
  productId: number | undefined;
  productTagInsert: common_ProductTagInsert | undefined;
};

export type DeleteProductByIDRequest = {
  id: number | undefined;
};

export type DeleteProductByIDResponse = {
};

export type UpdateProductSizeStockRequest = {
  productId: number | undefined;
  sizeId: number | undefined;
  quantity: number | undefined;
};

export type UpdateProductSizeStockResponse = {
};

export type ListStockChangeHistoryRequest = {
  dateFrom: wellKnownTimestamp | undefined;
  dateTo: wellKnownTimestamp | undefined;
  productId: number | undefined;
  sizeId?: number;
  source: common_StockChangeSource | undefined;
  limit: number | undefined;
  offset: number | undefined;
  orderFactor?: common_OrderFactor;
};

export type common_StockChangeSource =
  | "STOCK_CHANGE_SOURCE_UNSPECIFIED"
  | "STOCK_CHANGE_SOURCE_ADMIN_ADD_PRODUCT"
  | "STOCK_CHANGE_SOURCE_ADMIN_UPDATE_PRODUCT"
  | "STOCK_CHANGE_SOURCE_ADMIN_UPDATE_SIZE_STOCK"
  | "STOCK_CHANGE_SOURCE_ORDER_PLACED"
  | "STOCK_CHANGE_SOURCE_ORDER_CANCELLED"
  | "STOCK_CHANGE_SOURCE_ORDER_EXPIRED"
  | "STOCK_CHANGE_SOURCE_ORDER_REFUNDED";
export type ListStockChangeHistoryResponse = {
  changes: common_StockChange[] | undefined;
  total: number | undefined;
};

export type common_StockChange = {
  id: number | undefined;
  productId: number | undefined;
  sizeId: number | undefined;
  quantityDelta: googletype_Decimal | undefined;
  quantityBefore: googletype_Decimal | undefined;
  quantityAfter: googletype_Decimal | undefined;
  source: common_StockChangeSource | undefined;
  orderId: number | undefined;
  orderUuid: string | undefined;
  createdAt: wellKnownTimestamp | undefined;
  adminUsername: string | undefined;
};

export type DeleteProductMediaRequest = {
  productId: number | undefined;
  mediaId: number | undefined;
};

export type DeleteProductMediaResponse = {
};

export type AddPromoRequest = {
  promo: common_PromoCodeInsert | undefined;
};

// PromoCodeInsert represents the nested structure within PromoCode
export type common_PromoCodeInsert = {
  code: string | undefined;
  freeShipping: boolean | undefined;
  discount: googletype_Decimal | undefined;
  expiration: wellKnownTimestamp | undefined;
  start: wellKnownTimestamp | undefined;
  allowed: boolean | undefined;
  voucher: boolean | undefined;
};

export type AddPromoResponse = {
};

export type ListPromosRequest = {
  limit: number | undefined;
  offset: number | undefined;
  orderFactor: common_OrderFactor | undefined;
};

export type ListPromosResponse = {
  promoCodes: common_PromoCode[] | undefined;
};

// PromoCode represents the promo_code table
export type common_PromoCode = {
  promoCodeInsert: common_PromoCodeInsert | undefined;
};

export type DeletePromoCodeRequest = {
  code: string | undefined;
};

export type DeletePromoCodeResponse = {
};

export type DisablePromoCodeRequest = {
  code: string | undefined;
};

export type DisablePromoCodeResponse = {
};

export type GetOrderByUUIDRequest = {
  orderUuid: string | undefined;
};

export type GetOrderByUUIDResponse = {
  order: common_OrderFull | undefined;
};

export type common_OrderFull = {
  order: common_Order | undefined;
  orderItems: common_OrderItem[] | undefined;
  refundedOrderItems: common_OrderItem[] | undefined;
  payment: common_Payment | undefined;
  shipment: common_Shipment | undefined;
  promoCode: common_PromoCode | undefined;
  buyer: common_Buyer | undefined;
  billing: common_Address | undefined;
  shipping: common_Address | undefined;
  statusHistory: common_OrderStatusHistory[] | undefined;
};

export type common_Order = {
  id: number | undefined;
  uuid: string | undefined;
  placed: wellKnownTimestamp | undefined;
  modified: wellKnownTimestamp | undefined;
  totalPrice: googletype_Decimal | undefined;
  currency: string | undefined;
  orderStatusId: number | undefined;
  promoId: number | undefined;
  refundReason: string | undefined;
  orderComment: string | undefined;
  refundedAmount: googletype_Decimal | undefined;
};

export type common_OrderItem = {
  id: number | undefined;
  orderId: number | undefined;
  thumbnail: string | undefined;
  blurhash: string | undefined;
  productPrice: string | undefined;
  productPriceWithSale: string | undefined;
  productSalePercentage: string | undefined;
  productBrand: string | undefined;
  slug: string | undefined;
  color: string | undefined;
  topCategoryId: number | undefined;
  subCategoryId: number | undefined;
  typeId: number | undefined;
  sku: string | undefined;
  preorder: wellKnownTimestamp | undefined;
  orderItem: common_OrderItemInsert | undefined;
  translations: common_ProductInsertTranslation[] | undefined;
};

export type common_OrderItemInsert = {
  productId: number | undefined;
  quantity: number | undefined;
  sizeId: number | undefined;
};

// Payment represents the payment table
export type common_Payment = {
  createdAt: wellKnownTimestamp | undefined;
  modifiedAt: wellKnownTimestamp | undefined;
  paymentInsert: common_PaymentInsert | undefined;
};

export type common_PaymentInsert = {
  paymentMethod: common_PaymentMethodNameEnum | undefined;
  transactionId: string | undefined;
  transactionAmount: googletype_Decimal | undefined;
  transactionAmountPaymentCurrency: googletype_Decimal | undefined;
  clientSecret: string | undefined;
  isTransactionDone: boolean | undefined;
  expiredAt: wellKnownTimestamp | undefined;
};

// Shipment represents the shipment table
export type common_Shipment = {
  cost: googletype_Decimal | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  carrierId: number | undefined;
  trackingCode: string | undefined;
  shippingDate: wellKnownTimestamp | undefined;
  estimatedArrivalDate: wellKnownTimestamp | undefined;
  freeShipping: boolean | undefined;
};

export type common_Buyer = {
  buyerInsert: common_BuyerInsert | undefined;
};

export type common_BuyerInsert = {
  firstName: string | undefined;
  lastName: string | undefined;
  email: string | undefined;
  phone: string | undefined;
  receivePromoEmails: boolean | undefined;
};

export type common_Address = {
  addressInsert: common_AddressInsert | undefined;
};

export type common_AddressInsert = {
  country: string | undefined;
  state: string | undefined;
  city: string | undefined;
  addressLineOne: string | undefined;
  addressLineTwo: string | undefined;
  company: string | undefined;
  postalCode: string | undefined;
};

export type common_OrderStatusHistory = {
  id: number | undefined;
  orderId: number | undefined;
  status: common_OrderStatusEnum | undefined;
  changedAt: wellKnownTimestamp | undefined;
  changedBy: string | undefined;
  notes: string | undefined;
};

export type SetTrackingNumberRequest = {
  orderUuid: string | undefined;
  trackingCode: string | undefined;
};

export type SetTrackingNumberResponse = {
};

export type ListOrdersRequest = {
  status: common_OrderStatusEnum | undefined;
  paymentMethod: common_PaymentMethodNameEnum | undefined;
  email: string | undefined;
  orderId: number | undefined;
  orderUuid: string | undefined;
  limit: number | undefined;
  offset: number | undefined;
  orderFactor: common_OrderFactor | undefined;
};

export type ListOrdersResponse = {
  orders: common_Order[] | undefined;
};

export type GetBusinessMetricsRequest = {
  period: string | undefined;
  endAt: wellKnownTimestamp | undefined;
  compareMode: CompareMode | undefined;
};

export type GetBusinessMetricsResponse = {
  metrics: BusinessMetrics | undefined;
};

export type BusinessMetrics = {
  period: TimeRange | undefined;
  comparePeriod: TimeRange | undefined;
  revenue: MetricWithComparison | undefined;
  ordersCount: MetricWithComparison | undefined;
  avgOrderValue: MetricWithComparison | undefined;
  itemsPerOrder: MetricWithComparison | undefined;
  refundRate: MetricWithComparison | undefined;
  promoUsageRate: MetricWithComparison | undefined;
  grossRevenue: MetricWithComparison | undefined;
  totalRefunded: MetricWithComparison | undefined;
  totalDiscount: MetricWithComparison | undefined;
  revenueByCountry: GeographyMetric[] | undefined;
  revenueByCity: GeographyMetric[] | undefined;
  revenueByRegion: RegionMetric[] | undefined;
  avgOrderByCountry: GeographyMetric[] | undefined;
  revenueByCurrency: CurrencyMetric[] | undefined;
  revenueByPaymentMethod: PaymentMethodMetric[] | undefined;
  topProductsByRevenue: ProductMetric[] | undefined;
  topProductsByQuantity: ProductMetric[] | undefined;
  revenueByCategory: CategoryMetric[] | undefined;
  crossSellPairs: CrossSellPair[] | undefined;
  newSubscribers: MetricWithComparison | undefined;
  repeatCustomersRate: MetricWithComparison | undefined;
  avgOrdersPerCustomer: MetricWithComparison | undefined;
  avgDaysBetweenOrders: MetricWithComparison | undefined;
  clvDistribution: CLVStats | undefined;
  revenueByPromo: PromoMetric[] | undefined;
  ordersByStatus: StatusCount[] | undefined;
  revenueByDay: TimeSeriesPoint[] | undefined;
  ordersByDay: TimeSeriesPoint[] | undefined;
  subscribersByDay: TimeSeriesPoint[] | undefined;
  grossRevenueByDay: TimeSeriesPoint[] | undefined;
  refundsByDay: TimeSeriesPoint[] | undefined;
  avgOrderValueByDay: TimeSeriesPoint[] | undefined;
  unitsSoldByDay: TimeSeriesPoint[] | undefined;
  newCustomersByDay: TimeSeriesPoint[] | undefined;
  returningCustomersByDay: TimeSeriesPoint[] | undefined;
  shippedByDay: TimeSeriesPoint[] | undefined;
  deliveredByDay: TimeSeriesPoint[] | undefined;
  revenueByDayCompare: TimeSeriesPoint[] | undefined;
  ordersByDayCompare: TimeSeriesPoint[] | undefined;
  subscribersByDayCompare: TimeSeriesPoint[] | undefined;
  grossRevenueByDayCompare: TimeSeriesPoint[] | undefined;
  refundsByDayCompare: TimeSeriesPoint[] | undefined;
  avgOrderValueByDayCompare: TimeSeriesPoint[] | undefined;
  unitsSoldByDayCompare: TimeSeriesPoint[] | undefined;
  newCustomersByDayCompare: TimeSeriesPoint[] | undefined;
  returningCustomersByDayCompare: TimeSeriesPoint[] | undefined;
  shippedByDayCompare: TimeSeriesPoint[] | undefined;
  deliveredByDayCompare: TimeSeriesPoint[] | undefined;
  // GA4 Traffic & Engagement
  sessions: MetricWithComparison | undefined;
  users: MetricWithComparison | undefined;
  newUsers: MetricWithComparison | undefined;
  pageViews: MetricWithComparison | undefined;
  bounceRate: MetricWithComparison | undefined;
  avgSessionDuration: MetricWithComparison | undefined;
  pagesPerSession: MetricWithComparison | undefined;
  conversionRate: MetricWithComparison | undefined;
  revenuePerSession: MetricWithComparison | undefined;
  sessionsByCountry: GeographySessionMetric[] | undefined;
  topProductsByViews: ProductViewMetric[] | undefined;
  trafficBySource: TrafficSourceMetric[] | undefined;
  trafficByDevice: DeviceMetric[] | undefined;
  sessionsByDay: TimeSeriesPoint[] | undefined;
  usersByDay: TimeSeriesPoint[] | undefined;
  pageViewsByDay: TimeSeriesPoint[] | undefined;
  conversionRateByDay: TimeSeriesPoint[] | undefined;
  sessionsByDayCompare: TimeSeriesPoint[] | undefined;
  usersByDayCompare: TimeSeriesPoint[] | undefined;
  pageViewsByDayCompare: TimeSeriesPoint[] | undefined;
  conversionRateByDayCompare: TimeSeriesPoint[] | undefined;
};

export type TimeRange = {
  from: wellKnownTimestamp | undefined;
  to: wellKnownTimestamp | undefined;
};

export type MetricWithComparison = {
  value: googletype_Decimal | undefined;
  compareValue: googletype_Decimal | undefined;
  changePct: number | undefined;
};

export type GeographyMetric = {
  country: string | undefined;
  state: string | undefined;
  city: string | undefined;
  value: googletype_Decimal | undefined;
  compareValue: googletype_Decimal | undefined;
  count: number | undefined;
  compareCount: number | undefined;
};

export type RegionMetric = {
  region: string | undefined;
  value: googletype_Decimal | undefined;
  count: number | undefined;
};

export type CurrencyMetric = {
  currency: string | undefined;
  value: googletype_Decimal | undefined;
  count: number | undefined;
};

export type PaymentMethodMetric = {
  paymentMethod: string | undefined;
  value: googletype_Decimal | undefined;
  count: number | undefined;
};

export type ProductMetric = {
  productId: number | undefined;
  productName: string | undefined;
  brand: string | undefined;
  value: googletype_Decimal | undefined;
  count: number | undefined;
};

export type CategoryMetric = {
  categoryId: number | undefined;
  categoryName: string | undefined;
  value: googletype_Decimal | undefined;
  count: number | undefined;
};

export type CrossSellPair = {
  productAId: number | undefined;
  productBId: number | undefined;
  productAName: string | undefined;
  productBName: string | undefined;
  count: number | undefined;
};

export type CLVStats = {
  mean: googletype_Decimal | undefined;
  median: googletype_Decimal | undefined;
  p90: googletype_Decimal | undefined;
};

export type PromoMetric = {
  promoCode: string | undefined;
  ordersCount: number | undefined;
  revenue: googletype_Decimal | undefined;
  avgDiscount: googletype_Decimal | undefined;
};

export type StatusCount = {
  statusName: string | undefined;
  count: number | undefined;
};

export type TimeSeriesPoint = {
  date: wellKnownTimestamp | undefined;
  value: googletype_Decimal | undefined;
  count: number | undefined;
};

export type GeographySessionMetric = {
  country: string | undefined;
  state: string | undefined;
  city: string | undefined;
  sessions: number | undefined;
  users: number | undefined;
};

export type ProductViewMetric = {
  productId: number | undefined;
  productName: string | undefined;
  brand: string | undefined;
  pageViews: number | undefined;
  sessions: number | undefined;
  addToCarts: number | undefined;
  purchases: number | undefined;
  conversionRate: number | undefined;
};

export type TrafficSourceMetric = {
  source: string | undefined;
  medium: string | undefined;
  sessions: number | undefined;
  users: number | undefined;
  revenue: googletype_Decimal | undefined;
};

export type DeviceMetric = {
  deviceCategory: string | undefined;
  sessions: number | undefined;
  users: number | undefined;
  conversionRate: number | undefined;
};

export type RefundOrderRequest = {
  orderUuid: string | undefined;
  // Only used when status is PendingReturn. Empty = full refund. Non-empty = partial refund for specified order_item IDs.
  orderItemIds: number[] | undefined;
  // Optional reason for the refund (stored in order for audit).
  reason: string | undefined;
};

export type RefundOrderResponse = {
};

export type DeliveredOrderRequest = {
  orderUuid: string | undefined;
};

export type DeliveredOrderResponse = {
};

export type CancelOrderRequest = {
  orderUuid: string | undefined;
};

export type CancelOrderResponse = {
};

export type AddOrderCommentRequest = {
  orderUuid: string | undefined;
  comment: string | undefined;
};

export type AddOrderCommentResponse = {
};

export type AddHeroRequest = {
  hero: common_HeroFullInsert | undefined;
};

export type common_HeroFullInsert = {
  entities: common_HeroEntityInsert[] | undefined;
  navFeatured: common_NavFeaturedInsert | undefined;
};

export type common_HeroEntityInsert = {
  type: common_HeroType | undefined;
  single: common_HeroSingleInsert | undefined;
  double: common_HeroDoubleInsert | undefined;
  main: common_HeroMainInsert | undefined;
  featuredProducts: common_HeroFeaturedProductsInsert | undefined;
  featuredProductsTag: common_HeroFeaturedProductsTagInsert | undefined;
  featuredArchive: common_HeroFeaturedArchiveInsert | undefined;
};

export type common_HeroType =
  | "HERO_TYPE_UNKNOWN"
  | "HERO_TYPE_SINGLE"
  | "HERO_TYPE_DOUBLE"
  | "HERO_TYPE_MAIN"
  | "HERO_TYPE_FEATURED_PRODUCTS"
  | "HERO_TYPE_FEATURED_PRODUCTS_TAG"
  | "HERO_TYPE_FEATURED_ARCHIVE";
export type common_HeroSingleInsert = {
  mediaPortraitId: number | undefined;
  mediaLandscapeId: number | undefined;
  exploreLink: string | undefined;
  translations: common_HeroSingleInsertTranslation[] | undefined;
};

export type common_HeroSingleInsertTranslation = {
  languageId: number | undefined;
  headline: string | undefined;
  exploreText: string | undefined;
};

export type common_HeroDoubleInsert = {
  left: common_HeroSingleInsert | undefined;
  right: common_HeroSingleInsert | undefined;
};

export type common_HeroMainInsert = {
  mediaPortraitId: number | undefined;
  mediaLandscapeId: number | undefined;
  exploreLink: string | undefined;
  translations: common_HeroMainInsertTranslation[] | undefined;
};

export type common_HeroMainInsertTranslation = {
  languageId: number | undefined;
  tag: string | undefined;
  description: string | undefined;
  headline: string | undefined;
  exploreText: string | undefined;
};

export type common_HeroFeaturedProductsInsert = {
  productIds: number[] | undefined;
  exploreLink: string | undefined;
  translations: common_HeroFeaturedProductsInsertTranslation[] | undefined;
};

export type common_HeroFeaturedProductsInsertTranslation = {
  languageId: number | undefined;
  headline: string | undefined;
  exploreText: string | undefined;
};

export type common_HeroFeaturedProductsTagInsert = {
  tag: string | undefined;
  translations: common_HeroFeaturedProductsTagInsertTranslation[] | undefined;
};

export type common_HeroFeaturedProductsTagInsertTranslation = {
  languageId: number | undefined;
  headline: string | undefined;
  exploreText: string | undefined;
};

export type common_HeroFeaturedArchiveInsert = {
  archiveId: number | undefined;
  tag: string | undefined;
  translations: common_HeroFeaturedArchiveInsertTranslation[] | undefined;
};

export type common_HeroFeaturedArchiveInsertTranslation = {
  languageId: number | undefined;
  headline: string | undefined;
  exploreText: string | undefined;
};

export type common_NavFeaturedInsert = {
  men: common_NavFeaturedEntityInsert | undefined;
  women: common_NavFeaturedEntityInsert | undefined;
};

export type common_NavFeaturedEntityInsert = {
  mediaId: number | undefined;
  featuredTag: string | undefined;
  featuredArchiveId: number | undefined;
  translations: common_NavFeaturedEntityInsertTranslation[] | undefined;
};

export type common_NavFeaturedEntityInsertTranslation = {
  languageId: number | undefined;
  exploreText: string | undefined;
};

export type AddHeroResponse = {
};

export type AddArchiveRequest = {
  archiveInsert: common_ArchiveInsert | undefined;
};

export type common_ArchiveInsert = {
  tag: string | undefined;
  mediaIds: number[] | undefined;
  mainMediaIds: number[] | undefined;
  thumbnailId: number | undefined;
  translations: common_ArchiveInsertTranslation[] | undefined;
};

export type common_ArchiveInsertTranslation = {
  languageId: number | undefined;
  heading: string | undefined;
  description: string | undefined;
};

export type AddArchiveResponse = {
  id: number | undefined;
};

export type UpdateArchiveRequest = {
  id: number | undefined;
  archiveInsert: common_ArchiveInsert | undefined;
};

export type GetArchiveByIDRequest = {
  id: number | undefined;
};

export type GetArchiveByIDResponse = {
  archive: common_ArchiveFull | undefined;
};

export type common_ArchiveFull = {
  archiveList: common_ArchiveList | undefined;
  mainMedia: common_MediaFull[] | undefined;
  media: common_MediaFull[] | undefined;
};

export type common_ArchiveList = {
  id: number | undefined;
  translations: common_ArchiveInsertTranslation[] | undefined;
  tag: string | undefined;
  slug: string | undefined;
  createdAt: wellKnownTimestamp | undefined;
  thumbnail: common_MediaFull | undefined;
};

export type UpdateArchiveResponse = {
};

export type DeleteArchiveByIdRequest = {
  id: number | undefined;
};

export type DeleteArchiveByIdResponse = {
};

export type UpdateSettingsRequest = {
  shipmentCarriers: ShipmentCarrierAllowancePrice[] | undefined;
  paymentMethods: PaymentMethodAllowance[] | undefined;
  siteAvailable: boolean | undefined;
  maxOrderItems: number | undefined;
  bigMenu: boolean | undefined;
  announce: common_Announce | undefined;
  orderExpirationSeconds: number | undefined;
  complimentaryShippingPrices: { [key: string]: googletype_Decimal } | undefined;
  isProd: boolean | undefined;
};

export type ShipmentCarrierAllowancePrice = {
  carrier: string | undefined;
  allow: boolean | undefined;
  prices: { [key: string]: googletype_Decimal } | undefined;
};

export type PaymentMethodAllowance = {
  paymentMethod: common_PaymentMethodNameEnum | undefined;
  allow: boolean | undefined;
};

export type UpdateSettingsResponse = {
};

export type AddShipmentCarrierRequest = {
  carrier: string | undefined;
  prices: { [key: string]: googletype_Decimal } | undefined;
  trackingUrl: string | undefined;
  expectedDeliveryTime: string | undefined;
  description: string | undefined;
  allowedRegions: common_ShippingRegion[] | undefined;
  allowed: boolean | undefined;
};

export type AddShipmentCarrierResponse = {
  id: number | undefined;
};

export type UpdateShipmentCarrierRequest = {
  id: number | undefined;
  carrier: string | undefined;
  prices: { [key: string]: googletype_Decimal } | undefined;
  trackingUrl: string | undefined;
  expectedDeliveryTime: string | undefined;
  description: string | undefined;
  allowedRegions: common_ShippingRegion[] | undefined;
  allowed: boolean | undefined;
};

export type UpdateShipmentCarrierResponse = {
};

export type DeleteShipmentCarrierRequest = {
  id: number | undefined;
};

export type DeleteShipmentCarrierResponse = {
};

export type GetSupportTicketsPagedRequest = {
  limit: number | undefined;
  offset: number | undefined;
  orderFactor: common_OrderFactor | undefined;
  status?: common_SupportTicketStatus;
  email?: string;
  orderReference?: string;
  topic?: string;
  category?: string;
  priority?: common_SupportTicketPriority;
  dateFrom?: string;
  dateTo?: string;
};

export type common_SupportTicketStatus =
  | "SUPPORT_TICKET_STATUS_UNKNOWN"
  | "SUPPORT_TICKET_STATUS_SUBMITTED"
  | "SUPPORT_TICKET_STATUS_IN_PROGRESS"
  | "SUPPORT_TICKET_STATUS_WAITING_CUSTOMER"
  | "SUPPORT_TICKET_STATUS_RESOLVED"
  | "SUPPORT_TICKET_STATUS_CLOSED";
export type common_SupportTicketPriority =
  | "SUPPORT_TICKET_PRIORITY_UNKNOWN"
  | "SUPPORT_TICKET_PRIORITY_LOW"
  | "SUPPORT_TICKET_PRIORITY_MEDIUM"
  | "SUPPORT_TICKET_PRIORITY_HIGH"
  | "SUPPORT_TICKET_PRIORITY_URGENT";
export type GetSupportTicketsPagedResponse = {
  tickets: common_SupportTicket[] | undefined;
  totalCount: number | undefined;
};

export type common_SupportTicket = {
  id: number | undefined;
  createdAt: wellKnownTimestamp | undefined;
  updatedAt: wellKnownTimestamp | undefined;
  status: common_SupportTicketStatus | undefined;
  resolvedAt: wellKnownTimestamp | undefined;
  supportTicketInsert: common_SupportTicketInsert | undefined;
  caseNumber: string | undefined;
  category: string | undefined;
  priority: common_SupportTicketPriority | undefined;
  internalNotes: string | undefined;
};

export type common_SupportTicketInsert = {
  topic: string | undefined;
  subject: string | undefined;
  civility: string | undefined;
  email: string | undefined;
  firstName: string | undefined;
  lastName: string | undefined;
  orderReference: string | undefined;
  notes: string | undefined;
  category: string | undefined;
  priority: common_SupportTicketPriority | undefined;
};

export type GetSupportTicketByIdRequest = {
  id: number | undefined;
};

export type GetSupportTicketByIdResponse = {
  ticket: common_SupportTicket | undefined;
};

export type GetSupportTicketByCaseNumberRequest = {
  caseNumber: string | undefined;
};

export type GetSupportTicketByCaseNumberResponse = {
  ticket: common_SupportTicket | undefined;
};

export type UpdateSupportTicketStatusRequest = {
  id: number | undefined;
  status: common_SupportTicketStatus | undefined;
  internalNotes?: string;
};

export type UpdateSupportTicketStatusResponse = {
};

export type UpdateSupportTicketRequest = {
  id: number | undefined;
  priority?: common_SupportTicketPriority;
  category?: string;
  internalNotes?: string;
};

export type UpdateSupportTicketResponse = {
};

export interface AdminService {
  // Retrieves a key-value dictionary.
  GetDictionary(request: GetDictionaryRequest): Promise<GetDictionaryResponse>;
  // UploadContentImage uploads an image to a specific folder with a specified name.
  UploadContentImage(request: UploadContentImageRequest): Promise<UploadContentImageResponse>;
  // UploadContentVideo uploads a video to a specific folder with a specified name.
  UploadContentVideo(request: UploadContentVideoRequest): Promise<UploadContentVideoResponse>;
  // DeleteFromBucket deletes objects specified by their keys.
  DeleteFromBucket(request: DeleteFromBucketRequest): Promise<DeleteFromBucketResponse>;
  // ListObjectsPaged lists all objects in the base folder.
  ListObjectsPaged(request: ListObjectsPagedRequest): Promise<ListObjectsPagedResponse>;
  // Adds a new product or updates an existing one.
  UpsertProduct(request: UpsertProductRequest): Promise<UpsertProductResponse>;
  // Retrieves a paginated list of products.
  GetProductsPaged(request: GetProductsPagedRequest): Promise<GetProductsPagedResponse>;
  // Gets a product by its ID.
  GetProductByID(request: GetProductByIDRequest): Promise<GetProductByIDResponse>;
  // Deletes a product by its ID.
  DeleteProductByID(request: DeleteProductByIDRequest): Promise<DeleteProductByIDResponse>;
  // Updates the stock for a specific product size.
  UpdateProductSizeStock(request: UpdateProductSizeStockRequest): Promise<UpdateProductSizeStockResponse>;
  // Lists stock change history with optional filters.
  ListStockChangeHistory(request: ListStockChangeHistoryRequest): Promise<ListStockChangeHistoryResponse>;
  // Adds a new promotional code
  AddPromo(request: AddPromoRequest): Promise<AddPromoResponse>;
  // Lists all promotional codes
  ListPromos(request: ListPromosRequest): Promise<ListPromosResponse>;
  // Deletes a specific promotional code
  DeletePromoCode(request: DeletePromoCodeRequest): Promise<DeletePromoCodeResponse>;
  // Disables a specific promotional code
  DisablePromoCode(request: DisablePromoCodeRequest): Promise<DisablePromoCodeResponse>;
  // Retrieves an order by its ID
  GetOrderByUUID(request: GetOrderByUUIDRequest): Promise<GetOrderByUUIDResponse>;
  // Updates shipping information for an order
  SetTrackingNumber(request: SetTrackingNumberRequest): Promise<SetTrackingNumberResponse>;
  // Retrieves orders by their status payment method or email
  ListOrders(request: ListOrdersRequest): Promise<ListOrdersResponse>;
  // Processes a refund for an order
  RefundOrder(request: RefundOrderRequest): Promise<RefundOrderResponse>;
  // Marks an order as delivered
  DeliveredOrder(request: DeliveredOrderRequest): Promise<DeliveredOrderResponse>;
  // Retrieves business metrics for a period with optional comparison period
  GetBusinessMetrics(request: GetBusinessMetricsRequest): Promise<GetBusinessMetricsResponse>;
  // Cancels an order
  CancelOrder(request: CancelOrderRequest): Promise<CancelOrderResponse>;
  // Adds a comment to an order
  AddOrderComment(request: AddOrderCommentRequest): Promise<AddOrderCommentResponse>;
  // Adds a new hero
  AddHero(request: AddHeroRequest): Promise<AddHeroResponse>;
  // AddArchive creates a new archive.
  AddArchive(request: AddArchiveRequest): Promise<AddArchiveResponse>;
  UpdateArchive(request: UpdateArchiveRequest): Promise<UpdateArchiveResponse>;
  // DeleteArchiveById deletes an archive by ID.
  DeleteArchiveById(request: DeleteArchiveByIdRequest): Promise<DeleteArchiveByIdResponse>;
  GetArchiveByID(request: GetArchiveByIDRequest): Promise<GetArchiveByIDResponse>;
  UpdateSettings(request: UpdateSettingsRequest): Promise<UpdateSettingsResponse>;
  // AddShipmentCarrier adds a new shipping carrier.
  AddShipmentCarrier(request: AddShipmentCarrierRequest): Promise<AddShipmentCarrierResponse>;
  // UpdateShipmentCarrier updates an existing shipping carrier.
  UpdateShipmentCarrier(request: UpdateShipmentCarrierRequest): Promise<UpdateShipmentCarrierResponse>;
  // DeleteShipmentCarrier deletes a shipping carrier by ID.
  DeleteShipmentCarrier(request: DeleteShipmentCarrierRequest): Promise<DeleteShipmentCarrierResponse>;
  GetSupportTicketById(request: GetSupportTicketByIdRequest): Promise<GetSupportTicketByIdResponse>;
  GetSupportTicketByCaseNumber(request: GetSupportTicketByCaseNumberRequest): Promise<GetSupportTicketByCaseNumberResponse>;
  GetSupportTicketsPaged(request: GetSupportTicketsPagedRequest): Promise<GetSupportTicketsPagedResponse>;
  UpdateSupportTicketStatus(request: UpdateSupportTicketStatusRequest): Promise<UpdateSupportTicketStatusResponse>;
  UpdateSupportTicket(request: UpdateSupportTicketRequest): Promise<UpdateSupportTicketResponse>;
}

type RequestType = {
  path: string;
  method: string;
  body: string | null;
};

type RequestHandler = (request: RequestType, meta: { service: string, method: string }) => Promise<unknown>;

export function createAdminServiceClient(
  handler: RequestHandler
): AdminService {
  return {
    GetDictionary(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/dictionary`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetDictionary",
      }) as Promise<GetDictionaryResponse>;
    },
    UploadContentImage(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/content/image`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UploadContentImage",
      }) as Promise<UploadContentImageResponse>;
    },
    UploadContentVideo(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/content/video`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UploadContentVideo",
      }) as Promise<UploadContentVideoResponse>;
    },
    DeleteFromBucket(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/content`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.id) {
        queryParams.push(`id=${encodeURIComponent(request.id.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "DELETE",
        body,
      }, {
        service: "AdminService",
        method: "DeleteFromBucket",
      }) as Promise<DeleteFromBucketResponse>;
    },
    ListObjectsPaged(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/content`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.limit) {
        queryParams.push(`limit=${encodeURIComponent(request.limit.toString())}`)
      }
      if (request.offset) {
        queryParams.push(`offset=${encodeURIComponent(request.offset.toString())}`)
      }
      if (request.orderFactor) {
        queryParams.push(`orderFactor=${encodeURIComponent(request.orderFactor.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "ListObjectsPaged",
      }) as Promise<ListObjectsPagedResponse>;
    },
    UpsertProduct(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/product/upsert`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UpsertProduct",
      }) as Promise<UpsertProductResponse>;
    },
    GetProductsPaged(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/products/paged`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.limit) {
        queryParams.push(`limit=${encodeURIComponent(request.limit.toString())}`)
      }
      if (request.offset) {
        queryParams.push(`offset=${encodeURIComponent(request.offset.toString())}`)
      }
      if (request.sortFactors) {
        request.sortFactors.forEach((x) => {
          queryParams.push(`sortFactors=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.orderFactor) {
        queryParams.push(`orderFactor=${encodeURIComponent(request.orderFactor.toString())}`)
      }
      if (request.filterConditions?.from) {
        queryParams.push(`filterConditions.from=${encodeURIComponent(request.filterConditions.from.toString())}`)
      }
      if (request.filterConditions?.to) {
        queryParams.push(`filterConditions.to=${encodeURIComponent(request.filterConditions.to.toString())}`)
      }
      if (request.filterConditions?.currency) {
        queryParams.push(`filterConditions.currency=${encodeURIComponent(request.filterConditions.currency.toString())}`)
      }
      if (request.filterConditions?.onSale) {
        queryParams.push(`filterConditions.onSale=${encodeURIComponent(request.filterConditions.onSale.toString())}`)
      }
      if (request.filterConditions?.gender) {
        request.filterConditions.gender.forEach((x) => {
          queryParams.push(`filterConditions.gender=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.color) {
        queryParams.push(`filterConditions.color=${encodeURIComponent(request.filterConditions.color.toString())}`)
      }
      if (request.filterConditions?.topCategoryIds) {
        request.filterConditions.topCategoryIds.forEach((x) => {
          queryParams.push(`filterConditions.topCategoryIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.subCategoryIds) {
        request.filterConditions.subCategoryIds.forEach((x) => {
          queryParams.push(`filterConditions.subCategoryIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.typeIds) {
        request.filterConditions.typeIds.forEach((x) => {
          queryParams.push(`filterConditions.typeIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.sizesIds) {
        request.filterConditions.sizesIds.forEach((x) => {
          queryParams.push(`filterConditions.sizesIds=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.filterConditions?.preorder) {
        queryParams.push(`filterConditions.preorder=${encodeURIComponent(request.filterConditions.preorder.toString())}`)
      }
      if (request.filterConditions?.byTag) {
        queryParams.push(`filterConditions.byTag=${encodeURIComponent(request.filterConditions.byTag.toString())}`)
      }
      if (request.filterConditions?.collections) {
        request.filterConditions.collections.forEach((x) => {
          queryParams.push(`filterConditions.collections=${encodeURIComponent(x.toString())}`)
        })
      }
      if (request.showHidden) {
        queryParams.push(`showHidden=${encodeURIComponent(request.showHidden.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetProductsPaged",
      }) as Promise<GetProductsPagedResponse>;
    },
    GetProductByID(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/admin/product/${request.id}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetProductByID",
      }) as Promise<GetProductByIDResponse>;
    },
    DeleteProductByID(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/admin/product/${request.id}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "DELETE",
        body,
      }, {
        service: "AdminService",
        method: "DeleteProductByID",
      }) as Promise<DeleteProductByIDResponse>;
    },
    UpdateProductSizeStock(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.productId) {
        throw new Error("missing required field request.product_id");
      }
      if (!request.sizeId) {
        throw new Error("missing required field request.size_id");
      }
      const path = `api/admin/product/${request.productId}/size/${request.sizeId}/updatestock`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UpdateProductSizeStock",
      }) as Promise<UpdateProductSizeStockResponse>;
    },
    ListStockChangeHistory(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/stock-change-history`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.dateFrom) {
        queryParams.push(`dateFrom=${encodeURIComponent(request.dateFrom.toString())}`)
      }
      if (request.dateTo) {
        queryParams.push(`dateTo=${encodeURIComponent(request.dateTo.toString())}`)
      }
      if (request.productId) {
        queryParams.push(`productId=${encodeURIComponent(request.productId.toString())}`)
      }
      if (request.sizeId) {
        queryParams.push(`sizeId=${encodeURIComponent(request.sizeId.toString())}`)
      }
      if (request.source) {
        queryParams.push(`source=${encodeURIComponent(request.source.toString())}`)
      }
      if (request.limit) {
        queryParams.push(`limit=${encodeURIComponent(request.limit.toString())}`)
      }
      if (request.offset) {
        queryParams.push(`offset=${encodeURIComponent(request.offset.toString())}`)
      }
      if (request.orderFactor) {
        queryParams.push(`orderFactor=${encodeURIComponent(request.orderFactor.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "ListStockChangeHistory",
      }) as Promise<ListStockChangeHistoryResponse>;
    },
    AddPromo(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/promo/add`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "AddPromo",
      }) as Promise<AddPromoResponse>;
    },
    ListPromos(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/promo/list`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.limit) {
        queryParams.push(`limit=${encodeURIComponent(request.limit.toString())}`)
      }
      if (request.offset) {
        queryParams.push(`offset=${encodeURIComponent(request.offset.toString())}`)
      }
      if (request.orderFactor) {
        queryParams.push(`orderFactor=${encodeURIComponent(request.orderFactor.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "ListPromos",
      }) as Promise<ListPromosResponse>;
    },
    DeletePromoCode(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.code) {
        throw new Error("missing required field request.code");
      }
      const path = `api/admin/promo/${request.code}/delete`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "DELETE",
        body,
      }, {
        service: "AdminService",
        method: "DeletePromoCode",
      }) as Promise<DeletePromoCodeResponse>;
    },
    DisablePromoCode(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.code) {
        throw new Error("missing required field request.code");
      }
      const path = `api/admin/promo/${request.code}/disable`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "DisablePromoCode",
      }) as Promise<DisablePromoCodeResponse>;
    },
    GetOrderByUUID(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/admin/order/${request.orderUuid}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetOrderByUUID",
      }) as Promise<GetOrderByUUIDResponse>;
    },
    SetTrackingNumber(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/admin/orders/${request.orderUuid}/set-tracking-number`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "SetTrackingNumber",
      }) as Promise<SetTrackingNumberResponse>;
    },
    ListOrders(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/orders/list`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "ListOrders",
      }) as Promise<ListOrdersResponse>;
    },
    RefundOrder(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/admin/orders/${request.orderUuid}/refund`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "RefundOrder",
      }) as Promise<RefundOrderResponse>;
    },
    DeliveredOrder(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/admin/orders/${request.orderUuid}/delivered`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "DeliveredOrder",
      }) as Promise<DeliveredOrderResponse>;
    },
    GetBusinessMetrics(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/metrics`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.period) {
        queryParams.push(`period=${encodeURIComponent(request.period.toString())}`)
      }
      if (request.endAt) {
        queryParams.push(`endAt=${encodeURIComponent(request.endAt.toString())}`)
      }
      if (request.compareMode) {
        queryParams.push(`compareMode=${encodeURIComponent(request.compareMode.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetBusinessMetrics",
      }) as Promise<GetBusinessMetricsResponse>;
    },
    CancelOrder(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/admin/orders/${request.orderUuid}/cancel`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "CancelOrder",
      }) as Promise<CancelOrderResponse>;
    },
    AddOrderComment(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.orderUuid) {
        throw new Error("missing required field request.order_uuid");
      }
      const path = `api/admin/orders/${request.orderUuid}/comment`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "AddOrderComment",
      }) as Promise<AddOrderCommentResponse>;
    },
    AddHero(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/hero/add`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "AddHero",
      }) as Promise<AddHeroResponse>;
    },
    AddArchive(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/archive/add`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "AddArchive",
      }) as Promise<AddArchiveResponse>;
    },
    UpdateArchive(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/archive/update`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UpdateArchive",
      }) as Promise<UpdateArchiveResponse>;
    },
    DeleteArchiveById(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/admin/archive/${request.id}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "DELETE",
        body,
      }, {
        service: "AdminService",
        method: "DeleteArchiveById",
      }) as Promise<DeleteArchiveByIdResponse>;
    },
    GetArchiveByID(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/admin/archive/${request.id}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetArchiveByID",
      }) as Promise<GetArchiveByIDResponse>;
    },
    UpdateSettings(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/settings/update`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UpdateSettings",
      }) as Promise<UpdateSettingsResponse>;
    },
    AddShipmentCarrier(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/settings/shipment-carrier/add`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "AddShipmentCarrier",
      }) as Promise<AddShipmentCarrierResponse>;
    },
    UpdateShipmentCarrier(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/settings/shipment-carrier/update`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UpdateShipmentCarrier",
      }) as Promise<UpdateShipmentCarrierResponse>;
    },
    DeleteShipmentCarrier(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/admin/settings/shipment-carrier/${request.id}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "DELETE",
        body,
      }, {
        service: "AdminService",
        method: "DeleteShipmentCarrier",
      }) as Promise<DeleteShipmentCarrierResponse>;
    },
    GetSupportTicketById(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/admin/support/tickets/${request.id}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetSupportTicketById",
      }) as Promise<GetSupportTicketByIdResponse>;
    },
    GetSupportTicketByCaseNumber(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.caseNumber) {
        throw new Error("missing required field request.case_number");
      }
      const path = `api/admin/support/tickets/case/${request.caseNumber}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetSupportTicketByCaseNumber",
      }) as Promise<GetSupportTicketByCaseNumberResponse>;
    },
    GetSupportTicketsPaged(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      const path = `api/admin/support/tickets/paged`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      if (request.limit) {
        queryParams.push(`limit=${encodeURIComponent(request.limit.toString())}`)
      }
      if (request.offset) {
        queryParams.push(`offset=${encodeURIComponent(request.offset.toString())}`)
      }
      if (request.orderFactor) {
        queryParams.push(`orderFactor=${encodeURIComponent(request.orderFactor.toString())}`)
      }
      if (request.status) {
        queryParams.push(`status=${encodeURIComponent(request.status.toString())}`)
      }
      if (request.email) {
        queryParams.push(`email=${encodeURIComponent(request.email.toString())}`)
      }
      if (request.orderReference) {
        queryParams.push(`orderReference=${encodeURIComponent(request.orderReference.toString())}`)
      }
      if (request.topic) {
        queryParams.push(`topic=${encodeURIComponent(request.topic.toString())}`)
      }
      if (request.category) {
        queryParams.push(`category=${encodeURIComponent(request.category.toString())}`)
      }
      if (request.priority) {
        queryParams.push(`priority=${encodeURIComponent(request.priority.toString())}`)
      }
      if (request.dateFrom) {
        queryParams.push(`dateFrom=${encodeURIComponent(request.dateFrom.toString())}`)
      }
      if (request.dateTo) {
        queryParams.push(`dateTo=${encodeURIComponent(request.dateTo.toString())}`)
      }
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "AdminService",
        method: "GetSupportTicketsPaged",
      }) as Promise<GetSupportTicketsPagedResponse>;
    },
    UpdateSupportTicketStatus(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/admin/support/tickets/${request.id}/update-status`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UpdateSupportTicketStatus",
      }) as Promise<UpdateSupportTicketStatusResponse>;
    },
    UpdateSupportTicket(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.id) {
        throw new Error("missing required field request.id");
      }
      const path = `api/admin/support/tickets/${request.id}/update`; // eslint-disable-line quotes
      const body = JSON.stringify(request);
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "POST",
        body,
      }, {
        service: "AdminService",
        method: "UpdateSupportTicket",
      }) as Promise<UpdateSupportTicketResponse>;
    },
  };
}

// @@protoc_insertion_point(typescript-http-eof)
