import { common_CategoryEnum, common_MeasurementNameEnum } from "api/proto-http/admin";

export const categoryMeasurementsMapping: { [key in common_CategoryEnum]?: common_MeasurementNameEnum[] } = {
    CATEGORY_ENUM_T_SHIRT: [
        "MEASUREMENT_NAME_ENUM_SHOULDERS",
        "MEASUREMENT_NAME_ENUM_SLEEVE",
        "MEASUREMENT_NAME_ENUM_WAIST",
        "MEASUREMENT_NAME_ENUM_LENGTH",
    ],
    CATEGORY_ENUM_JEANS: [
        "MEASUREMENT_NAME_ENUM_WAIST",
        "MEASUREMENT_NAME_ENUM_INSEAM",
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_RISE",
        "MEASUREMENT_NAME_ENUM_HIPS",
    ],
    CATEGORY_ENUM_DRESS: [
        "MEASUREMENT_NAME_ENUM_SHOULDERS",
        "MEASUREMENT_NAME_ENUM_BUST",
        'MEASUREMENT_NAME_ENUM_WAIST',
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_SLEEVE"
    ],
    CATEGORY_ENUM_JACKET: [
        "MEASUREMENT_NAME_ENUM_SHOULDERS",
        "MEASUREMENT_NAME_ENUM_BUST",
        'MEASUREMENT_NAME_ENUM_WAIST',
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_SLEEVE"
    ],
    CATEGORY_ENUM_SWEATER: [
        "MEASUREMENT_NAME_ENUM_SHOULDERS",
        "MEASUREMENT_NAME_ENUM_BUST",
        'MEASUREMENT_NAME_ENUM_WAIST',
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_SLEEVE"
    ],
    CATEGORY_ENUM_PANT: [
        'MEASUREMENT_NAME_ENUM_WAIST',
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_RISE",
        "MEASUREMENT_NAME_ENUM_HIPS",
        "MEASUREMENT_NAME_ENUM_INSEAM"
    ],
    CATEGORY_ENUM_SKIRT: [
        'MEASUREMENT_NAME_ENUM_WAIST',
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_HIPS",
    ],
    CATEGORY_ENUM_SHORT: [
        'MEASUREMENT_NAME_ENUM_WAIST',
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_RISE",
        "MEASUREMENT_NAME_ENUM_HIPS",
        "MEASUREMENT_NAME_ENUM_INSEAM"
    ],
    CATEGORY_ENUM_BLAZER: [
        "MEASUREMENT_NAME_ENUM_SHOULDERS",
        "MEASUREMENT_NAME_ENUM_BUST",
        'MEASUREMENT_NAME_ENUM_WAIST',
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_SLEEVE"
    ],
    CATEGORY_ENUM_COAT: [
        "MEASUREMENT_NAME_ENUM_SHOULDERS",
        "MEASUREMENT_NAME_ENUM_BUST",
        'MEASUREMENT_NAME_ENUM_WAIST',
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_SLEEVE"
    ],
    CATEGORY_ENUM_UNDERWEAR: [
        "MEASUREMENT_NAME_ENUM_WAIST",
        "MEASUREMENT_NAME_ENUM_HIPS"
    ],
    CATEGORY_ENUM_BRA: [
        "MEASUREMENT_NAME_ENUM_BUST"
    ],
    CATEGORY_ENUM_SCARF: [
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_WIDTH"
    ],
    CATEGORY_ENUM_BELT: [
        "MEASUREMENT_NAME_ENUM_WAIST",
        "MEASUREMENT_NAME_ENUM_LENGTH"
    ],
    CATEGORY_ENUM_OTHER: [
        "MEASUREMENT_NAME_ENUM_LENGTH",
        "MEASUREMENT_NAME_ENUM_WIDTH"
    ],
    CATEGORY_ENUM_BAG: [
        "MEASUREMENT_NAME_ENUM_HEIGHT",
        "MEASUREMENT_NAME_ENUM_WIDTH"
    ]

};