export enum ROUTES {
  login = '/',
  error = '/error',
  main = '/main',
  media = '/media-manager',
  product = '/product-manager',
  addProduct = '/add-product',
  singleProduct = '/product',
  hero = '/hero',
  addHero = '/add-hero',
  getHero = '/get-hero',
  promo = '/promo',
  getPromo = '/get-promo',
  archive = '/archive',
  createArchive = '/create-archive',
  getArchive = '/get-archive',
  settings = '/settings',
  orders = '/orders',
  orderDetails = '/orders/:id',
}
