// Package resend provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package resend

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CreateApiKeyRequestPermission.
const (
	FullAccess    CreateApiKeyRequestPermission = "full_access"
	SendingAccess CreateApiKeyRequestPermission = "sending_access"
)

// Defines values for CreateDomainRequestRegion.
const (
	EuWest1 CreateDomainRequestRegion = "eu-west-1"
	SaEast1 CreateDomainRequestRegion = "sa-east-1"
	UsEast1 CreateDomainRequestRegion = "us-east-1"
)

// ApiKey defines model for ApiKey.
type ApiKey struct {
	// CreatedAt The date and time the API key was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id The ID of the API key.
	Id *string `json:"id,omitempty"`

	// Name The name of the API key.
	Name *string `json:"name,omitempty"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	// Content Content of an attached file.
	Content *openapi_types.File `json:"content,omitempty"`

	// Filename Name of attached file.
	Filename *string `json:"filename,omitempty"`

	// Path Path where the attachment file is hosted
	Path *string `json:"path,omitempty"`
}

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	// DomainId Restrict an API key to send emails only from a specific domain. Only used when the permission is sending_acces.
	DomainId *string `json:"domain_id,omitempty"`

	// Name The API key name.
	Name string `json:"name"`

	// Permission The API key can have full access to Resend’s API or be only restricted to send emails. * full_access - Can create, delete, get, and update any resource. * sending_access - Can only send emails.
	Permission *CreateApiKeyRequestPermission `json:"permission,omitempty"`
}

// CreateApiKeyRequestPermission The API key can have full access to Resend’s API or be only restricted to send emails. * full_access - Can create, delete, get, and update any resource. * sending_access - Can only send emails.
type CreateApiKeyRequestPermission string

// CreateApiKeyResponse defines model for CreateApiKeyResponse.
type CreateApiKeyResponse struct {
	// Id The ID of the API key.
	Id *string `json:"id,omitempty"`

	// Token The token of the API key.
	Token *string `json:"token,omitempty"`
}

// CreateBatchEmailsResponse defines model for CreateBatchEmailsResponse.
type CreateBatchEmailsResponse struct {
	Data *[]struct {
		// Id The ID of the sent email.
		Id *string `json:"id,omitempty"`
	} `json:"data,omitempty"`
}

// CreateDomainRequest defines model for CreateDomainRequest.
type CreateDomainRequest struct {
	// Name The name of the domain you want to create.
	Name string `json:"name"`

	// Region The region where emails will be sent from. Possible values are us-east-1' | 'eu-west-1' | 'sa-east-1
	Region *CreateDomainRequestRegion `json:"region,omitempty"`
}

// CreateDomainRequestRegion The region where emails will be sent from. Possible values are us-east-1' | 'eu-west-1' | 'sa-east-1
type CreateDomainRequestRegion string

// CreateDomainResponse defines model for CreateDomainResponse.
type CreateDomainResponse struct {
	// CreatedAt The date and time the domain was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id The ID of the domain.
	Id *string `json:"id,omitempty"`

	// Name The name of the domain.
	Name    *string         `json:"name,omitempty"`
	Records *[]DomainRecord `json:"records,omitempty"`

	// Region The region where the domain is hosted.
	Region *string `json:"region,omitempty"`

	// Status The status of the domain.
	Status *string `json:"status,omitempty"`
}

// DeleteDomainResponse defines model for DeleteDomainResponse.
type DeleteDomainResponse struct {
	// Deleted Indicates whether the domain was deleted successfully.
	Deleted *bool `json:"deleted,omitempty"`

	// Id The ID of the domain.
	Id *string `json:"id,omitempty"`

	// Object The type of object.
	Object *string `json:"object,omitempty"`
}

// Domain defines model for Domain.
type Domain struct {
	// CreatedAt The date and time the domain was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id The ID of the domain.
	Id *string `json:"id,omitempty"`

	// Name The name of the domain.
	Name *string `json:"name,omitempty"`

	// Object The type of object.
	Object  *string         `json:"object,omitempty"`
	Records *[]DomainRecord `json:"records,omitempty"`

	// Region The region where the domain is hosted.
	Region *string `json:"region,omitempty"`

	// Status The status of the domain.
	Status *string `json:"status,omitempty"`
}

// DomainRecord defines model for DomainRecord.
type DomainRecord struct {
	// Name The name of the record.
	Name *string `json:"name,omitempty"`

	// Priority The priority of the record.
	Priority *int `json:"priority,omitempty"`

	// Record The type of record.
	Record *string `json:"record,omitempty"`

	// Status The status of the record.
	Status *string `json:"status,omitempty"`

	// Ttl The time to live for the record.
	Ttl *string `json:"ttl,omitempty"`

	// Type The type of record.
	Type *string `json:"type,omitempty"`

	// Value The value of the record.
	Value *string `json:"value,omitempty"`
}

// Email defines model for Email.
type Email struct {
	// Bcc The email addresses of the blind carbon copy recipients.
	Bcc *[]string `json:"bcc,omitempty"`

	// Cc The email addresses of the carbon copy recipients.
	Cc *[]string `json:"cc,omitempty"`

	// CreatedAt The date and time the email was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// From The email address of the sender.
	From *string `json:"from,omitempty"`

	// Html The HTML body of the email.
	Html *string `json:"html,omitempty"`

	// Id The ID of the email.
	Id *string `json:"id,omitempty"`

	// LastEvent The status of the email.
	LastEvent *string `json:"last_event,omitempty"`

	// Object The type of object.
	Object *string `json:"object,omitempty"`

	// ReplyTo The email addresses to which replies should be sent.
	ReplyTo *[]string `json:"reply_to,omitempty"`

	// Subject The subject line of the email.
	Subject *string `json:"subject,omitempty"`

	// Text The plain text body of the email.
	Text *string   `json:"text,omitempty"`
	To   *[]string `json:"to,omitempty"`
}

// ListApiKeysResponse defines model for ListApiKeysResponse.
type ListApiKeysResponse struct {
	Data *[]ApiKey `json:"data,omitempty"`
}

// ListDomainsItem defines model for ListDomainsItem.
type ListDomainsItem struct {
	// CreatedAt The date and time the domain was created.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Id The ID of the domain.
	Id *string `json:"id,omitempty"`

	// Name The name of the domain.
	Name *string `json:"name,omitempty"`

	// Region The region where the domain is hosted.
	Region *string `json:"region,omitempty"`

	// Status The status of the domain.
	Status *string `json:"status,omitempty"`
}

// ListDomainsResponse defines model for ListDomainsResponse.
type ListDomainsResponse struct {
	Data *[]ListDomainsItem `json:"data,omitempty"`
}

// SendEmailRequest defines model for SendEmailRequest.
type SendEmailRequest struct {
	Attachments *[]Attachment `json:"attachments,omitempty"`

	// Bcc Bcc recipient email address. For multiple addresses, send as an array of strings.
	Bcc *string `json:"bcc,omitempty"`

	// Cc Cc recipient email address. For multiple addresses, send as an array of strings.
	Cc *string `json:"cc,omitempty"`

	// From Sender email address. To include a friendly name, use the format "Your Name <sender@domain.com>".
	From string `json:"from"`

	// Headers Custom headers to add to the email.
	Headers *map[string]interface{} `json:"headers,omitempty"`

	// Html The HTML version of the message.
	Html *string `json:"html,omitempty"`

	// ReplyTo Reply-to email address. For multiple addresses, send as an array of strings.
	ReplyTo *string `json:"reply_to,omitempty"`

	// Subject Email subject.
	Subject string `json:"subject"`
	Tags    *[]Tag `json:"tags,omitempty"`

	// Text The plain text version of the message.
	Text *string  `json:"text,omitempty"`
	To   []string `json:"to"`
}

// SendEmailResponse defines model for SendEmailResponse.
type SendEmailResponse struct {
	// Id The ID of the sent email.
	Id *string `json:"id,omitempty"`
}

// Tag defines model for Tag.
type Tag struct {
	// Name The name of the email tag. It can only contain ASCII letters (a–z, A–Z), numbers (0–9), underscores (_), or dashes (-). It can contain no more than 256 characters.
	Name *string `json:"name,omitempty"`

	// Value The value of the email tag.It can only contain ASCII letters (a–z, A–Z), numbers (0–9), underscores (_), or dashes (-). It can contain no more than 256 characters.
	Value *string `json:"value,omitempty"`
}

// VerifyDomainResponse defines model for VerifyDomainResponse.
type VerifyDomainResponse struct {
	// Id The ID of the domain.
	Id *string `json:"id,omitempty"`

	// Object The type of object.
	Object *string `json:"object,omitempty"`
}

// PostEmailsBatchJSONBody defines parameters for PostEmailsBatch.
type PostEmailsBatchJSONBody = []SendEmailRequest

// PostApiKeysJSONRequestBody defines body for PostApiKeys for application/json ContentType.
type PostApiKeysJSONRequestBody = CreateApiKeyRequest

// PostDomainsJSONRequestBody defines body for PostDomains for application/json ContentType.
type PostDomainsJSONRequestBody = CreateDomainRequest

// PostEmailsJSONRequestBody defines body for PostEmails for application/json ContentType.
type PostEmailsJSONRequestBody = SendEmailRequest

// PostEmailsBatchJSONRequestBody defines body for PostEmailsBatch for application/json ContentType.
type PostEmailsBatchJSONRequestBody = PostEmailsBatchJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiKeys request
	GetApiKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiKeysWithBody request with any body
	PostApiKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiKeys(ctx context.Context, body PostApiKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiKeysApiKeyId request
	DeleteApiKeysApiKeyId(ctx context.Context, apiKeyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDomains request
	GetDomains(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostDomainsWithBody request with any body
	PostDomainsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDomains(ctx context.Context, body PostDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDomainsDomainId request
	DeleteDomainsDomainId(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDomainsDomainId request
	GetDomainsDomainId(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostDomainsDomainIdVerify request
	PostDomainsDomainIdVerify(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEmailsWithBody request with any body
	PostEmailsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostEmails(ctx context.Context, body PostEmailsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostEmailsBatchWithBody request with any body
	PostEmailsBatchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostEmailsBatch(ctx context.Context, body PostEmailsBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEmailsEmailId request
	GetEmailsEmailId(ctx context.Context, emailId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiKeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiKeysWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiKeysRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiKeys(ctx context.Context, body PostApiKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiKeysRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiKeysApiKeyId(ctx context.Context, apiKeyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiKeysApiKeyIdRequest(c.Server, apiKeyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDomains(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDomainsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDomainsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDomainsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDomains(ctx context.Context, body PostDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDomainsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteDomainsDomainId(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDomainsDomainIdRequest(c.Server, domainId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDomainsDomainId(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDomainsDomainIdRequest(c.Server, domainId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDomainsDomainIdVerify(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDomainsDomainIdVerifyRequest(c.Server, domainId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEmailsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEmailsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEmails(ctx context.Context, body PostEmailsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEmailsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEmailsBatchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEmailsBatchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostEmailsBatch(ctx context.Context, body PostEmailsBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostEmailsBatchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEmailsEmailId(ctx context.Context, emailId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEmailsEmailIdRequest(c.Server, emailId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiKeysRequest generates requests for GetApiKeys
func NewGetApiKeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiKeysRequest calls the generic PostApiKeys builder with application/json body
func NewPostApiKeysRequest(server string, body PostApiKeysJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiKeysRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiKeysRequestWithBody generates requests for PostApiKeys with any type of body
func NewPostApiKeysRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiKeysApiKeyIdRequest generates requests for DeleteApiKeysApiKeyId
func NewDeleteApiKeysApiKeyIdRequest(server string, apiKeyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "api_key_id", runtime.ParamLocationPath, apiKeyId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api-keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDomainsRequest generates requests for GetDomains
func NewGetDomainsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostDomainsRequest calls the generic PostDomains builder with application/json body
func NewPostDomainsRequest(server string, body PostDomainsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDomainsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostDomainsRequestWithBody generates requests for PostDomains with any type of body
func NewPostDomainsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDomainsDomainIdRequest generates requests for DeleteDomainsDomainId
func NewDeleteDomainsDomainIdRequest(server string, domainId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "domain_id", runtime.ParamLocationPath, domainId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDomainsDomainIdRequest generates requests for GetDomainsDomainId
func NewGetDomainsDomainIdRequest(server string, domainId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "domain_id", runtime.ParamLocationPath, domainId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostDomainsDomainIdVerifyRequest generates requests for PostDomainsDomainIdVerify
func NewPostDomainsDomainIdVerifyRequest(server string, domainId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "domain_id", runtime.ParamLocationPath, domainId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/verify", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostEmailsRequest calls the generic PostEmails builder with application/json body
func NewPostEmailsRequest(server string, body PostEmailsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEmailsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostEmailsRequestWithBody generates requests for PostEmails with any type of body
func NewPostEmailsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/emails")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostEmailsBatchRequest calls the generic PostEmailsBatch builder with application/json body
func NewPostEmailsBatchRequest(server string, body PostEmailsBatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostEmailsBatchRequestWithBody(server, "application/json", bodyReader)
}

// NewPostEmailsBatchRequestWithBody generates requests for PostEmailsBatch with any type of body
func NewPostEmailsBatchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/emails/batch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetEmailsEmailIdRequest generates requests for GetEmailsEmailId
func NewGetEmailsEmailIdRequest(server string, emailId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "email_id", runtime.ParamLocationPath, emailId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/emails/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiKeysWithResponse request
	GetApiKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiKeysResponse, error)

	// PostApiKeysWithBodyWithResponse request with any body
	PostApiKeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiKeysResponse, error)

	PostApiKeysWithResponse(ctx context.Context, body PostApiKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiKeysResponse, error)

	// DeleteApiKeysApiKeyIdWithResponse request
	DeleteApiKeysApiKeyIdWithResponse(ctx context.Context, apiKeyId string, reqEditors ...RequestEditorFn) (*DeleteApiKeysApiKeyIdResponse, error)

	// GetDomainsWithResponse request
	GetDomainsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDomainsResponse, error)

	// PostDomainsWithBodyWithResponse request with any body
	PostDomainsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDomainsResponse, error)

	PostDomainsWithResponse(ctx context.Context, body PostDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDomainsResponse, error)

	// DeleteDomainsDomainIdWithResponse request
	DeleteDomainsDomainIdWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*DeleteDomainsDomainIdResponse, error)

	// GetDomainsDomainIdWithResponse request
	GetDomainsDomainIdWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*GetDomainsDomainIdResponse, error)

	// PostDomainsDomainIdVerifyWithResponse request
	PostDomainsDomainIdVerifyWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*PostDomainsDomainIdVerifyResponse, error)

	// PostEmailsWithBodyWithResponse request with any body
	PostEmailsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEmailsResponse, error)

	PostEmailsWithResponse(ctx context.Context, body PostEmailsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEmailsResponse, error)

	// PostEmailsBatchWithBodyWithResponse request with any body
	PostEmailsBatchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEmailsBatchResponse, error)

	PostEmailsBatchWithResponse(ctx context.Context, body PostEmailsBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEmailsBatchResponse, error)

	// GetEmailsEmailIdWithResponse request
	GetEmailsEmailIdWithResponse(ctx context.Context, emailId string, reqEditors ...RequestEditorFn) (*GetEmailsEmailIdResponse, error)
}

type GetApiKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListApiKeysResponse
}

// Status returns HTTPResponse.Status
func (r GetApiKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateApiKeyResponse
}

// Status returns HTTPResponse.Status
func (r PostApiKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiKeysApiKeyIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteApiKeysApiKeyIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiKeysApiKeyIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListDomainsResponse
}

// Status returns HTTPResponse.Status
func (r GetDomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostDomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateDomainResponse
}

// Status returns HTTPResponse.Status
func (r PostDomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteDomainsDomainIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeleteDomainResponse
}

// Status returns HTTPResponse.Status
func (r DeleteDomainsDomainIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDomainsDomainIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDomainsDomainIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Domain
}

// Status returns HTTPResponse.Status
func (r GetDomainsDomainIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDomainsDomainIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostDomainsDomainIdVerifyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VerifyDomainResponse
}

// Status returns HTTPResponse.Status
func (r PostDomainsDomainIdVerifyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDomainsDomainIdVerifyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostEmailsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SendEmailResponse
}

// Status returns HTTPResponse.Status
func (r PostEmailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEmailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostEmailsBatchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateBatchEmailsResponse
}

// Status returns HTTPResponse.Status
func (r PostEmailsBatchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostEmailsBatchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEmailsEmailIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Email
}

// Status returns HTTPResponse.Status
func (r GetEmailsEmailIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEmailsEmailIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetApiKeysWithResponse request returning *GetApiKeysResponse
func (c *ClientWithResponses) GetApiKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiKeysResponse, error) {
	rsp, err := c.GetApiKeys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiKeysResponse(rsp)
}

// PostApiKeysWithBodyWithResponse request with arbitrary body returning *PostApiKeysResponse
func (c *ClientWithResponses) PostApiKeysWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiKeysResponse, error) {
	rsp, err := c.PostApiKeysWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiKeysResponse(rsp)
}

func (c *ClientWithResponses) PostApiKeysWithResponse(ctx context.Context, body PostApiKeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiKeysResponse, error) {
	rsp, err := c.PostApiKeys(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiKeysResponse(rsp)
}

// DeleteApiKeysApiKeyIdWithResponse request returning *DeleteApiKeysApiKeyIdResponse
func (c *ClientWithResponses) DeleteApiKeysApiKeyIdWithResponse(ctx context.Context, apiKeyId string, reqEditors ...RequestEditorFn) (*DeleteApiKeysApiKeyIdResponse, error) {
	rsp, err := c.DeleteApiKeysApiKeyId(ctx, apiKeyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiKeysApiKeyIdResponse(rsp)
}

// GetDomainsWithResponse request returning *GetDomainsResponse
func (c *ClientWithResponses) GetDomainsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDomainsResponse, error) {
	rsp, err := c.GetDomains(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDomainsResponse(rsp)
}

// PostDomainsWithBodyWithResponse request with arbitrary body returning *PostDomainsResponse
func (c *ClientWithResponses) PostDomainsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDomainsResponse, error) {
	rsp, err := c.PostDomainsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDomainsResponse(rsp)
}

func (c *ClientWithResponses) PostDomainsWithResponse(ctx context.Context, body PostDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDomainsResponse, error) {
	rsp, err := c.PostDomains(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDomainsResponse(rsp)
}

// DeleteDomainsDomainIdWithResponse request returning *DeleteDomainsDomainIdResponse
func (c *ClientWithResponses) DeleteDomainsDomainIdWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*DeleteDomainsDomainIdResponse, error) {
	rsp, err := c.DeleteDomainsDomainId(ctx, domainId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDomainsDomainIdResponse(rsp)
}

// GetDomainsDomainIdWithResponse request returning *GetDomainsDomainIdResponse
func (c *ClientWithResponses) GetDomainsDomainIdWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*GetDomainsDomainIdResponse, error) {
	rsp, err := c.GetDomainsDomainId(ctx, domainId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDomainsDomainIdResponse(rsp)
}

// PostDomainsDomainIdVerifyWithResponse request returning *PostDomainsDomainIdVerifyResponse
func (c *ClientWithResponses) PostDomainsDomainIdVerifyWithResponse(ctx context.Context, domainId string, reqEditors ...RequestEditorFn) (*PostDomainsDomainIdVerifyResponse, error) {
	rsp, err := c.PostDomainsDomainIdVerify(ctx, domainId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDomainsDomainIdVerifyResponse(rsp)
}

// PostEmailsWithBodyWithResponse request with arbitrary body returning *PostEmailsResponse
func (c *ClientWithResponses) PostEmailsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEmailsResponse, error) {
	rsp, err := c.PostEmailsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEmailsResponse(rsp)
}

func (c *ClientWithResponses) PostEmailsWithResponse(ctx context.Context, body PostEmailsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEmailsResponse, error) {
	rsp, err := c.PostEmails(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEmailsResponse(rsp)
}

// PostEmailsBatchWithBodyWithResponse request with arbitrary body returning *PostEmailsBatchResponse
func (c *ClientWithResponses) PostEmailsBatchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostEmailsBatchResponse, error) {
	rsp, err := c.PostEmailsBatchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEmailsBatchResponse(rsp)
}

func (c *ClientWithResponses) PostEmailsBatchWithResponse(ctx context.Context, body PostEmailsBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostEmailsBatchResponse, error) {
	rsp, err := c.PostEmailsBatch(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostEmailsBatchResponse(rsp)
}

// GetEmailsEmailIdWithResponse request returning *GetEmailsEmailIdResponse
func (c *ClientWithResponses) GetEmailsEmailIdWithResponse(ctx context.Context, emailId string, reqEditors ...RequestEditorFn) (*GetEmailsEmailIdResponse, error) {
	rsp, err := c.GetEmailsEmailId(ctx, emailId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEmailsEmailIdResponse(rsp)
}

// ParseGetApiKeysResponse parses an HTTP response from a GetApiKeysWithResponse call
func ParseGetApiKeysResponse(rsp *http.Response) (*GetApiKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListApiKeysResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiKeysResponse parses an HTTP response from a PostApiKeysWithResponse call
func ParsePostApiKeysResponse(rsp *http.Response) (*PostApiKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateApiKeyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteApiKeysApiKeyIdResponse parses an HTTP response from a DeleteApiKeysApiKeyIdWithResponse call
func ParseDeleteApiKeysApiKeyIdResponse(rsp *http.Response) (*DeleteApiKeysApiKeyIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiKeysApiKeyIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetDomainsResponse parses an HTTP response from a GetDomainsWithResponse call
func ParseGetDomainsResponse(rsp *http.Response) (*GetDomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListDomainsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostDomainsResponse parses an HTTP response from a PostDomainsWithResponse call
func ParsePostDomainsResponse(rsp *http.Response) (*PostDomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateDomainResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteDomainsDomainIdResponse parses an HTTP response from a DeleteDomainsDomainIdWithResponse call
func ParseDeleteDomainsDomainIdResponse(rsp *http.Response) (*DeleteDomainsDomainIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDomainsDomainIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeleteDomainResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetDomainsDomainIdResponse parses an HTTP response from a GetDomainsDomainIdWithResponse call
func ParseGetDomainsDomainIdResponse(rsp *http.Response) (*GetDomainsDomainIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDomainsDomainIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Domain
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostDomainsDomainIdVerifyResponse parses an HTTP response from a PostDomainsDomainIdVerifyWithResponse call
func ParsePostDomainsDomainIdVerifyResponse(rsp *http.Response) (*PostDomainsDomainIdVerifyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDomainsDomainIdVerifyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VerifyDomainResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostEmailsResponse parses an HTTP response from a PostEmailsWithResponse call
func ParsePostEmailsResponse(rsp *http.Response) (*PostEmailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEmailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SendEmailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostEmailsBatchResponse parses an HTTP response from a PostEmailsBatchWithResponse call
func ParsePostEmailsBatchResponse(rsp *http.Response) (*PostEmailsBatchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostEmailsBatchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateBatchEmailsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetEmailsEmailIdResponse parses an HTTP response from a GetEmailsEmailIdWithResponse call
func ParseGetEmailsEmailIdResponse(rsp *http.Response) (*GetEmailsEmailIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEmailsEmailIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Email
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
