/**
 * STEP 3 · FABRICS AND HARDWARE (`fabrics-hardware.tsx`) and the slot / binding model it shares
 * with FABRIC RENDER (`slot-fabrics.ts`). `patternOutputs` and friends stay exported for ARTIFACTS.
 */
export { FabricsHardware, type FabricsHardwareProps } from './fabrics-hardware';
export { CornerLabel, FABRIC_CELL_ASPECT, PendingTile, TiledFace } from './organs';
export {
  PATTERN,
  REFUSAL_ADVICE,
  REPEAT_MAX,
  SEAM_CODE,
  SEAM_WORDS,
  normaliseRepeat,
  patternAssets,
  patternOutputs,
  patternRuns,
  pictureFull,
  pictureThumb,
  refusalAdvice,
  repeatOfRun,
  seamWarningOf,
  shelfIsFull,
} from './model';
export {
  NO_BINDINGS_REASON,
  READ_ONLY_RUN_REASON,
  READ_ONLY_SHELF_REASON,
  SILENT_SERVER_REASON,
  SLOT_WORDS_MAX,
  bindingOf,
  bindingsOf,
  bindingsSpoken,
  boundAsset,
  boundAssetsByPair,
  clothSlots,
  materialSlots,
  clothTwin,
  colourIsStated,
  imageGate,
  mintFabricName,
  mintSlotName,
  pairKey,
  pairOfRun,
  pairsOfAsset,
  recentFabrics,
  rowColour,
  shelfCeiling,
  slotSuggestions,
  slotUsage,
  slotUsageRow,
  swatchColour,
  swatchGate,
  type BomLineLike,
  type ClothSlot,
  type ClothSlots,
  type MaterialSlot,
  type MaterialSlots,
  type ShelfCeiling,
  type SlotUsage,
  type SwatchColour,
} from './slot-fabrics';
