// Точка входа пробы истории жестов: esbuild бандлит только с файла, а модуль чистый — одного
// реэкспорта хватает.
export {
  HISTORY_DEPTH,
  appendLabel,
  canRedo,
  canUndo,
  dissolveLabel,
  dropForm,
  dropMove,
  dropRedoTop,
  emptyHistory,
  isFormEntry,
  moveLabel,
  peekRedo,
  peekUndo,
  pushUndo,
  record,
  redoStep,
  redoTitle,
  renameLabel,
  resolvePending,
  undoStep,
  undoTitle,
} from '../src/components/managers/tech-card/components/last-mutation';
